// MODULE: writes the per-folder MAP.md files (and MAP.<file>.md outlines for big files) from the graph.
// Output is deterministic — no dates, no absolute paths, everything sorted — so `check` can compare it byte for byte.
import path from 'node:path';

const dirOf = (rel) => (path.posix.dirname(rel) === '.' ? '' : path.posix.dirname(rel));
const slash = (d) => (d ? `${d}/` : '');
const n = (x) => x.toLocaleString('en-US');

export function renderMaps(graph, ctx) {
  const { cfg, docs, repoName, command } = ctx;
  const recs = graph.files;
  const plan = planFolders([...recs.keys()], cfg);
  const out = new Map(); // output path → content

  // which map each file is listed in, and which folder map owns each folder
  const mapOfFile = new Map();
  for (const d of plan.mapped) for (const f of plan.held.get(d)) mapOfFile.set(f, d);
  const mapPath = (d) => `${slash(d)}${cfg.mapName}`;

  const folderStats = new Map();
  const statsOf = (d) => {
    if (folderStats.has(d)) return folderStats.get(d);
    const files = [...recs.keys()].filter((f) => d === '' || f.startsWith(d + '/'));
    const tags = countTags(files.map((f) => recs.get(f)));
    const usedBy = new Set();
    for (const f of files) for (const u of recs.get(f).users) if (!(d === '' || u.startsWith(d + '/'))) usedBy.add(mapOfFile.get(u) ?? dirOf(u));
    const s = { files: files.length, tags, usedBy: [...usedBy].sort() };
    folderStats.set(d, s);
    return s;
  };

  for (const d of [...plan.mapped].sort()) {
    const files = plan.held.get(d).slice().sort();
    const kids = plan.childMaps.get(d) || [];
    const head = [];
    if (d === '') {
      head.push(`# MAP — ${repoName}`);
      head.push(`Generated by \`${command} generate\` — don't edit by hand. Regenerated when a branch merges into the main branch; between merges, line numbers may have shifted — grep to confirm.`);
      head.push(`Find: \`grep -rn --include='MAP*.md' "<word>" .\` — or walk down from here through the \`map:\` links.`);
      if (cfg.systemMap) head.push(`How the parts interact (written, not generated): ${cfg.systemMap}`);
      head.push('Lines: `path:start-end  kind  signature  usage  [tags]`. Usage: used by N files · in file · entry (framework calls it) · tests only · unused.');
      head.push(`Tags: ${tagLine(graph.summary) || 'none'} — leads from reading the code, not verdicts: grep the name as plain text before deleting.`);
    } else {
      const purpose = folderPurpose(d, docs, ctx.readDoc);
      head.push(`# MAP · ${d}/${purpose ? ` — ${purpose}` : ''}`);
      const up = parentMap(d, plan.mapped);
      head.push(`Generated — don't edit. Up: ${mapPath(up)} · Find: \`grep -rn --include='MAP*.md' "<word>" .\``);
    }

    const folderLines = [];
    if (kids.length) {
      folderLines.push('', '## Folders');
      for (const k of kids) {
        const s = statsOf(k);
        const purpose = folderPurpose(k, docs, ctx.readDoc);
        const bits = [`${s.files} files`];
        if (s.usedBy.length) bits.push(`used by ${list(s.usedBy.map((u) => (u ? u + '/' : '(root)')), 3)}`);
        const t = tagLine(s.tags);
        if (t) bits.push(t);
        bits.push(`map: ${mapPath(k)}`);
        folderLines.push(`${k}/${purpose ? `  ${purpose}` : ''} · ${bits.join(' · ')}`);
      }
    }

    // "no tests" once for the folder when nothing here has tests, instead of on every file
    const anyTests = files.some((f) => recs.get(f).tests.size || recs.get(f).test);
    if (files.length && !anyTests) head.push('Tests: none cover the files listed here — verify changes by hand.');

    // outline big files first; then keep outlining the largest until the map fits
    const outlined = new Set(files.filter((f) => recs.get(f).symbols.length > cfg.outlineOver));
    const build = () => {
      const body = [];
      if (files.length) body.push('', '## Files');
      for (const f of files) body.push(...fileBlock(recs.get(f), { outlined: outlined.has(f), cfg, anyTests }));
      return [...head, ...folderLines, ...body];
    };
    let lines = build();
    while (lines.length > cfg.maxMapLines) {
      const next = files.filter((f) => !outlined.has(f) && recs.get(f).symbols.length >= 8)
        .sort((a, b) => recs.get(b).symbols.length - recs.get(a).symbols.length || a.localeCompare(b))[0];
      if (!next) break;
      outlined.add(next);
      lines = build();
    }
    out.set(mapPath(d), lines.join('\n') + '\n');
    for (const f of outlined) out.set(outlinePath(f), outlineFile(recs.get(f), { cfg, owner: mapPath(d) }));
  }
  return out;
}

export const outlinePath = (rel) => `${slash(dirOf(rel))}MAP.${path.posix.basename(rel)}.md`;

function fileBlock(r, { outlined, cfg, anyTests }) {
  const f = r.facts;
  const bits = [`${n(f.lines)} lines`];
  if (f.lines > cfg.largeFileLines) bits.push('large: read by range');
  if (r.test) bits.push('test');
  if (r.tests.size) bits.push(`tests: ${list([...r.tests].sort(), 2)}`);
  else if (!r.test && anyTests) bits.push('no tests');
  const t = tagLine(countTags([r]));
  if (t) bits.push(t);
  const lines = ['', `${r.rel}  ${bits.join(' · ')}`];
  if (f.purpose) lines.push(`  purpose   ${f.purpose}`);
  if (outlined) {
    const routes = [...r.routes, ...f.routes];
    if (routes.length) lines.push(`  routes    ${list(routes, 6)}`);
    lines.push(`  outline   ${outlinePath(r.rel)} — ${f.symbols.length} symbols, labels, keys`);
    return lines;
  }
  return [...lines, ...detailLines(r), ...r.symbols.map((s) => symLine(r.rel, s))];
}

function outlineFile(r, { cfg, owner }) {
  const f = r.facts;
  const lines = [
    `# MAP · ${r.rel} — outline`,
    `Generated — don't edit. Listed in ${owner} · ${n(f.lines)} lines${f.lines > cfg.largeFileLines ? ' · read by range, not whole' : ''}`,
  ];
  if (f.purpose) lines.push(`purpose   ${f.purpose}`);
  if (r.tests.size) lines.push(`tests     ${list([...r.tests].sort(), 6)}`);
  const details = detailLines(r).map((l) => l.replace(/^ {2}/, ''));
  lines.push(...details, '', '## Symbols', ...r.symbols.map((s) => symLine(r.rel, s)));
  return lines.join('\n') + '\n';
}

function detailLines(r) {
  const f = r.facts;
  const out = [];
  const routes = [...r.routes, ...f.routes];
  if (routes.length) out.push(`  routes    ${list(routes, 8)}`);
  if (f.fetches.length) out.push(`  calls     ${list(f.fetches, 8)}`);
  const data = [];
  if (f.tables.length) data.push(`tables ${f.tables.join(', ')}`);
  if (f.buckets.length) data.push(`buckets ${f.buckets.join(', ')}`);
  if (f.rpcs.length) data.push(`rpc ${f.rpcs.join(', ')}`);
  if (data.length) out.push(`  data      ${data.join(' · ')}${r.notInSchema.length ? `  [not in schema: ${r.notInSchema.join(', ')}]` : ''}`);
  const keys = [];
  if (f.storage.read.length) keys.push(`reads ${list(f.storage.read, 10)}`);
  if (f.storage.write.length) keys.push(`writes ${list(f.storage.write, 10)}`);
  if (keys.length) out.push(`  storage   ${keys.join(' · ')}`);
  const msgs = [];
  const handled = f.messages.handled.filter((v) => /^[a-z]+[A-Z]\w*$|^[A-Z][A-Z0-9_]{2,}$|^[\w-]+:[\w:-]+$/.test(v));
  const sent = f.messages.sent;
  if (handled.length) msgs.push(`handles ${list(handled, 10)}`);
  if (sent.length) msgs.push(`sends ${list(sent, 10)}`);
  if (msgs.length) out.push(`  messages  ${msgs.join(' · ')}`);
  for (const p of r.pairs) out.push(`  pair      ${p.kind} ${p.key}: ${p.issue}  [half-pair]`);
  if (f.labels.length) out.push(`  labels    ${list(f.labels.map((l) => `"${l}"`), 14)}`);
  for (const i of f.invariants) out.push(`  invariant ${r.rel}:${i.line}  ${i.text}`);
  if (r.tags.includes('unused-file')) out.push('  file      nothing imports, loads or names this file  [unused-file]');
  return out;
}

function symLine(rel, s) {
  const loc = s.start === s.end ? `${rel}:${s.start}` : `${rel}:${s.start}-${s.end}`;
  const tags = s.tags.length ? `  [${s.tags.join('] [')}]` : '';
  return `  ${loc}  ${s.kind.padEnd(6)} ${s.sig}  ${s.status}${tags}`;
}

// a folder gets its own map when it holds enough files (its own plus small subfolders folded in), or 2+ mapped subfolders
function planFolders(rels, cfg) {
  const direct = new Map();
  const children = new Map();
  const ensure = (d) => {
    if (children.has(d)) return;
    children.set(d, new Set());
    if (d !== '') { const p = dirOf(d); ensure(p); children.get(p).add(d); }
  };
  for (const rel of rels) {
    const d = dirOf(rel);
    ensure(d);
    if (!direct.has(d)) direct.set(d, []);
    direct.get(d).push(rel);
  }
  const depth = (d) => (d === '' ? 0 : d.split('/').length);
  const dirs = [...children.keys()].sort((a, b) => depth(b) - depth(a) || a.localeCompare(b));
  const mapped = new Set();
  const held = new Map();
  for (const d of dirs) {
    const files = [...(direct.get(d) || [])];
    let kidsMapped = 0;
    for (const c of children.get(d)) {
      if (mapped.has(c)) kidsMapped++;
      else files.push(...held.get(c));
    }
    held.set(d, files);
    if (d === '' || files.length >= cfg.minFilesForOwnMap || kidsMapped >= 2) mapped.add(d);
  }
  const nearest = (d) => [...children.get(d)].sort().flatMap((c) => (mapped.has(c) ? [c] : nearest(c)));
  const childMaps = new Map([...mapped].map((d) => [d, nearest(d)]));
  return { mapped, held: new Map([...mapped].map((d) => [d, held.get(d)])), childMaps };
}

function parentMap(d, mapped) {
  let p = dirOf(d);
  while (p !== '' && !mapped.has(p)) p = dirOf(p);
  return p;
}

export function folderPurpose(d, docs, readDoc) {
  for (const name of ['CLAUDE.md', 'README.md']) {
    const p = `${slash(d)}${name}`;
    if (!docs.has(p)) continue;
    const h = (readDoc(p).match(/^#\s+(.+)$/m) || [])[1];
    if (!h) continue;
    const clean = h.replace(/^`?[\w./-]+\/?`?\s*[—–:-]\s*/, '').trim();
    if (clean && clean.length <= 90) return clean;
  }
  return null;
}

function countTags(recs) {
  const c = {};
  for (const r of recs) {
    for (const s of r.symbols) for (const t of s.tags) { const k = t.startsWith('keep') ? 'keep' : t; c[k] = (c[k] || 0) + 1; }
    if (r.pairs.length) c['half-pair'] = (c['half-pair'] || 0) + r.pairs.length;
    if (r.notInSchema.length) c['not-in-schema'] = (c['not-in-schema'] || 0) + r.notInSchema.length;
    for (const t of r.tags) c[t] = (c[t] || 0) + 1;
  }
  return c;
}
const TAG_ORDER = ['unused', 'tests-only', 'half-pair', 'not-in-schema', 'unused-file', 'keep'];
function tagLine(c) {
  return TAG_ORDER.filter((k) => c[k]).map((k) => `${k} ${c[k]}`).join(' · ');
}
function list(items, max) {
  return items.length > max ? `${items.slice(0, max).join(', ')} +${items.length - max}` : items.join(', ');
}
