// MODULE: writes MAP.html — the whole map as one page a person opens in a browser, generated with the MAP.md files from the same graph.
// Deterministic like the MAP files, and one short record per line, so a repo-wide grep that hits it returns a small line, not a blob.
import fs from 'node:fs';
import path from 'node:path';
import { folderPurpose } from './render.mjs';
import { MESSAGE_LIKE } from './graph.mjs';

const TEMPLATE = fs.readFileSync(new URL('./viewer.html', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function renderView(graph, ctx) {
  const { cfg, docs, readDoc, repoName, command } = ctx;
  const rows = [['H', repoName, cfg.systemMap || '', command, cfg.largeFileLines]];
  const dirs = new Set();
  for (const rel of graph.files.keys()) for (let d = path.posix.dirname(rel); d !== '.' && !dirs.has(d); d = path.posix.dirname(d)) dirs.add(d);
  for (const d of [...dirs].sort()) { const p = folderPurpose(d, docs, readDoc); if (p) rows.push(['G', d, p]); }

  for (const rel of [...graph.files.keys()].sort()) {
    const r = graph.files.get(rel);
    const f = r.facts;
    rows.push(['F', rel, f.lines, r.test ? 1 : 0, r.tags.includes('unused-file') ? 1 : 0, f.purpose || '']);
    for (const t of [...r.tests].sort()) rows.push(['T', t]);
    for (const u of [...r.users].sort()) rows.push(['U', u]);
    for (const x of [...r.routes, ...f.routes]) rows.push(['R', x]);
    for (const x of f.fetches) rows.push(['C', x]);
    for (const x of f.tables) rows.push(['D', `table ${x}`]);
    for (const x of f.buckets) rows.push(['D', `bucket ${x}`]);
    for (const x of f.rpcs) rows.push(['D', `rpc ${x}`]);
    for (const x of r.notInSchema) rows.push(['N', x]);
    for (const k of f.storage.read) rows.push(['K', 'reads', k]);
    for (const k of f.storage.write) rows.push(['K', 'writes', k]);
    for (const m of f.messages.handled.filter((v) => MESSAGE_LIKE.test(v))) rows.push(['M', 'handles', m]);
    for (const m of f.messages.sent) rows.push(['M', 'sends', m]);
    for (const p of r.pairs) rows.push(['P', `${p.kind} ${p.key}: ${p.issue}`]);
    for (const l of f.labels) rows.push(['L', l]);
    for (const i of f.invariants) rows.push(['I', i.line, i.text]);
    for (const s of r.symbols) rows.push(['S', s.name, s.kind, s.start, s.end, s.sig, s.status, s.tags.join('|')]);
  }

  // `<` escaped so no string in the data can close the <script> it sits in
  const data = rows.map((row) => JSON.stringify(row).replace(/</g, '\\u003c')).join(',\n');
  const fill = { __COMMENT__: `generated by ${command} generate with the MAP.md files. Don't edit — open it in a browser.`.replace(/--/g, '- -'),
    __TITLE__: escapeHtml(repoName), __MAP_DATA__: data };
  // split/join, not replace(): the data may contain `$&` and similar replacement patterns
  return Object.entries(fill).reduce((html, [k, v]) => html.split(k).join(v), TEMPLATE);
}
